### ISSUE TITLE
Cannot use with multiple arguments/parameters

### ISSUE THREAD

**Issue by tbergeron** [ladinu/node-grep#1]
Hi,

I'm trying to use `node-grep` to run the following commands:
`grep -rI --exclude '^.{,100}$' keyword /path`

I tried:

``` javascript
grep(["-rI --exclude '^.{,100}$'", what, where], function(err, stdout, stderr) {
});
```

I also tried:

``` javascript
grep(['-rI', "--exclude='^.{,100}$'", what, where], function(err, stdout, stderr) {
});
```

but I always get:

```
 "grep: invalid option --  
usage: grep [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
```

![](http://cl.ly/image/29232Z1w0A06/Screen%20Shot%202014-05-22%20at%2010.11.38%20AM.png)

When I remove the --exclude and keep only -rI it works fine. I just wonder how to work with multiple arguments? Any suggestion/idea/example of how I should be handling this?

Thanks!

**Comment by ladinu** [comment]
Hi,

I have hw that I need to do first. I’ll probably look at your questions over the weekend and get back to you.

Thanks,
Ladinu

**Comment by tbergeron** [comment]
Awesome no stress, thanks :+1:

**Comment by ladinu** [comment]
Try this and see if it work

grep(["-rI", "--exclude",  "'^.{,100}$'", what, where], function(err,
stdout, stderr) { });

**Comment by tbergeron** [comment]
This seems to work, one thing I noticed since the beginning though: output results seem variably good. Sometimes I get the same thing as grep will give me but sometimes not at all.

It seems when there's too much results, it just outputs an error with no info:

```
[21526:0523/142728:INFO:CONSOLE(109)] "{} """, source: file:///Users/tommybergeron/Desktop/Projects/node-webkit-experiment/app/js/main.js (109)
// like 109 being console.log(err, stderr);
```

Any idea why this is happening? thanks for the response at least this part now works fine :+1:

**Comment by tbergeron** [comment]
Bumping this in case you forgot about me :+1:

**Comment by ladinu** [comment]
I'm sorry. I've been busy lately.

You are right. Your getting the error because the input is too large. You
should try using pipes instead of the callback method.

For example, try doing something like this:

var search = grep(['pattern', '/tmp/file']);

search.on('data', function (data){
    console.log(data);
});

search.on('error', function(err) { console.log(err); });
